name: Docker Build and Push

on:
  push:
    branches:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push PHP Image
        working-directory: ./DockerFile
        run: |
          docker build -t lightgaia19/php-image .
          docker push lightgaia19/php-image