# name: Docker Build and Push

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push Docker image
#         run: |
#           docker build -t lightgaia/biblion_docker_01:latest .
#           docker push lightgaia/biblion_docker_01:latest


name: Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Clean up old containers
      #   run: |
      #     docker ps -aq | xargs docker stop
      #     docker ps -aq | xargs docker rm

      - name: Build and push Docker images
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker build -t "web" -f Dockerfile .
          docker push "web"
