name: Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # - name: Clean up old containers
      #   run: |
      #     docker stop $(docker ps -q)
      #     docker rm $(docker ps -aq)

      - name: Build and push Client Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lightgaia19/biblion
          dockerfile: ./Dockerfile
          registry: docker.io
